{
 "title": "Device Activity",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pings",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(rate({job=\"telemetry\"} | json | country != `` [$__auto])))"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(host) (count by(host) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Device Pings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by(deviceBase) (count_over_time({job=\"telemetry\"} | json | country != `` [$__auto]))",
     "legendFormat": "{{deviceBase}}"
    }
   ]
  },
  {
   "title": "Device Count",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count by(deviceBase) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Country Count",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count by(country) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Device Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count by(device) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Country Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "count by(country) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Host Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "count by(host) (count_over_time({job=\"telemetry\"} | json | country != `` [$__range]))"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{job=\"telemetry\"} | json | country != ``"
    }
   ]
  }
 ]
}