networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    restart: unless-stopped
    volumes:
      - loki_storage:/loki

  promtail:
    image: grafana/promtail:2.9.10
    volumes:
      - ./promtail-config.yml:/etc/promtail/new-config.yml
      - data:/data
    command: -config.file=/etc/promtail/new-config.yml
    restart: unless-stopped
    networks:
      - loki

  grafana:
    environment:
      - GF_SERVER_ROOT_URL=http://linux.lan:4000
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - '4000:3000'
    networks:
      - loki
    restart: unless-stopped
    volumes:
      - grafana_storage:/var/lib/grafana
volumes:
  grafana_storage: {}
  loki_storage: {}
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.lan,nfsvers=4,soft,nolock"
      device: ":/mnt/data-pool/shared/osc-telemetry"
