server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: telemetry
    pipeline_stages:
      - json:
          expressions:
            date: date
            country: country
            device: device
            deviceBase: deviceBase
            deviceVersion: deviceVersion
            host: host
            os: os
            arch: arch
      - timestamp:
          source: date
          format: RFC3339Nano
    static_configs:
      - targets:
          - localhost
        labels:
          job: telemetry
          __path__: /data/*.txt
